server:
  host: 0.0.0.0
  port: 8000
security:
  user:
    name: "keyang"
    password: 1
logging:
  level:
    org.springframework: DEBUG
spring:
  datasource:
    url: "jdbc:mysql://192.168.1.71:3306/project"
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
