server:
  host: 127.0.0.1
  port: 8080
logging:
  level:
    org.springframework: DEBUG
    org.hibernate: DEBUG
    org.apache: DEBUG

spring:
  datasource:
    url: "jdbc:mysql://192.168.1.71:3306/project"
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
