package demo.model;

import demo.model.converter.LocalDateTimeConverter;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Created by Linda on 25/02/16.
 */
@Entity
@Table(name = "orders")
public class Order {
    // ------------------------
    // PRIVATE FIELDS
    // ------------------------

    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id = 0;

    @ManyToOne
    private User user;

    @OneToOne
    private Address address;

    //The order time
    @NotNull
    @Convert(converter = LocalDateTimeConverter.class)
    private Date order_date;

    //The product status
    @NotNull
    private String status;

    //The ship track no
    private String track_no;

    //The ship provider
    private String ship_method;

    @OneToMany
    @JoinColumn(name = "order_id")
    private List<OrderDetail> orderdetails = new ArrayList<>();
    // ------------------------
    // PUBLIC METHODS
    // ------------------------
    public Order() {}

    public Order(long id) {
        this.id = id;
    }

    public Order(User user, Address address, Date order_date, String status, String track_no, String ship_method, List<OrderDetail> orderdetails) {
        this.user = user;
        this.address = address;
        this.order_date = order_date;
        this.status = status;
        this.track_no = track_no;
        this.ship_method = ship_method;
        this.orderdetails = orderdetails;
    }


    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public Address getAddress() {
        return address;
    }

    public void setAddress(Address address) {
        this.address = address;
    }

    public Date getOrder_date() {
        return order_date;
    }

    public void setOrder_date(Date order_date) {
        this.order_date = order_date;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getTrack_no() {
        return track_no;
    }

    public void setTrack_no(String track_no) {
        this.track_no = track_no;
    }

    public String getShip_method() {
        return ship_method;
    }

    public void setShip_method(String ship_method) {
        this.ship_method = ship_method;
    }

    public List<OrderDetail> getOrderdetails() {
        return orderdetails;
    }

    public void setOrderdetails(List<OrderDetail> orderdetails) {
        this.orderdetails = orderdetails;
    }
}

