package demo.model;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 * Created by Linda on 21/02/16.
 */
@Entity
@Table(name = "product")
public class Product {
    // ------------------------
    // PRIVATE FIELDS
    // ------------------------

    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;

    //The product's brand
    @NotNull
    private  String brand;

    // The product's name
    @NotNull
    private String name;

    // The product's price
    @NotNull
    private String price;

    //The product's version
    private String version;

    //The product's weight
    private String weight;

    //The product's provider
    private String provider;

    public Product(String brand, String name, String price, String version, String weight, String provider) {
        this.brand = brand;
        this.name = name;
        this.price = price;
        this.version = version;
        this.weight = weight;
        this.provider = provider;
    }

    public String getBrand() {
        return brand;
    }

    public void setBrand(String brand) {
        this.brand = brand;
    }

    public String getVersion() {
        return version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    public String getProvider() {
        return provider;
    }

    public void setProvider(String provider) {
        this.provider = provider;
    }

    public String getWeight() {
        return weight;
    }

    public void setWeight(String weight) {
        this.weight = weight;
    }

    public String getPrice() {
        return price;
    }

    public void setPrice(String price) {
        this.price = price;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}



