package demo.model;

import demo.util.NullAwareBeanUtil;
import org.springframework.beans.BeanUtils;
import org.springframework.util.StringUtils;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 * Created by Linda on 21/02/16.
 */
@Entity
@Table(name = "product")
public class Product {
    // ------------------------
    // PRIVATE FIELDS
    // ------------------------

    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;

    //The product's brand
    @NotNull
    private  String brand;

    // The product's name
    @NotNull
    private String name;

    // The product's price
    @NotNull
    private String price;

    // The product's old price
    private String oldprice;

    // The product's instruction
    private String instruction;

    //The product's version
    private String version;

    //The product's weight
    private String weight;

    //The product's provider
    private String provider;

    //The product's picture link
    private String picturelink;

    //The product's quantity
    private int quantity;

    // ------------------------
    // PUBLIC METHODS
    // ------------------------
    public Product(){ }

    public Product(long id){this.id = id;}

    public Product(String brand, String name, String price, String oldprice, String instruction, String version, String weight, String provider, String picturelink, int quantity) {
        this.brand = brand;
        this.name = name;
        this.price = price;
        this.oldprice = oldprice;
        this.instruction = instruction;
        this.version = version;
        this.weight = weight;
        this.provider = provider;
        this.picturelink = picturelink;
        this.quantity = quantity;
    }

    public Product(ProductDTO productDTO) {
        this(productDTO.getBrand(),productDTO.getName(),productDTO.getPrice(),productDTO.getOldprice(),productDTO.getInstruction(),productDTO.getVersion(),productDTO.getWeight(),productDTO.getProvider(),productDTO.getPicturelink(),productDTO.getQuantity());
    }

    // Getter and setter methods


    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getBrand() {
        return brand;
    }

    public void setBrand(String brand) {
        this.brand = brand;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPrice() {
        return price;
    }

    public void setPrice(String price) {
        this.price = price;
    }

    public String getOldprice() {
        return oldprice;
    }

    public void setOldprice(String oldprice) {
        this.oldprice = oldprice;
    }

    public String getInstruction() {
        return instruction;
    }

    public void setInstruction(String instruction) {
        this.instruction = instruction;
    }

    public String getVersion() {
        return version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    public String getWeight() {
        return weight;
    }

    public void setWeight(String weight) {
        this.weight = weight;
    }

    public String getProvider() {
        return provider;
    }

    public void setProvider(String provider) {
        this.provider = provider;
    }

    public String getPicturelink() {
        return picturelink;
    }

    public void setPicturelink(String picturelink) {
        this.picturelink = picturelink;
    }

    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
}



